# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: example
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbpassword
    ports:
        - "3306:3306"